### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Yangjia23** [sunkint/splendor-ui#6]
👋你好，我也正在使用 vitpress 搭建文档，你把 .vitepress 与 docs 文件夹分开，是为了能找到文档服务能够找到 src 目录下的  install 方法嘛？

请问，如果我将 .vitepress 直接放到 docs 文件下，使用 `vitepress dev docs` 起的服务，怎么引入 src 下的 install ?
十分感谢

**Comment by sunkint** [comment]
参考 [https://github.com/sunkint/splendor-ui/blob/master/.vitepress/theme/index.js](https://github.com/sunkint/splendor-ui/blob/master/.vitepress/theme/index.js)
直接改一下引用路径可否？
